const netCryptoQsRaw = [
    ["[Dễ] Mô hình OSI có bao nhiêu tầng (layer)?", "A. 4", "B. 5", "C. 7", "D. 9", 2, "Mô hình Open Systems Interconnection chuẩn xác định 7 tầng từ Physical đến Application."],
    ["[Dễ] Địa chỉ IP hoạt động ở tầng nào của mô hình OSI?", "A. Tầng 2 (Data Link)", "B. Tầng 3 (Network)", "C. Tầng 4 (Transport)", "D. Tầng 7 (Application)", 1, "IP cung cấp định tuyến (Routing) giữa các mạng, là giao thức nòng cốt của Tầng 3."],
    ["[Dễ] Giao thức TCP khác UDP ở điểm quan trọng nhất nào?", "A. TCP nhanh hơn UDP", "B. TCP là giao thức hướng kết nối (Connection-oriented), đảm bảo truyền tin cậy; UDP thì không kết nối (Connectionless)", "C. UDP dùng cho Web, TCP dùng cho Game", "D. UDP mã hóa dữ liệu", 1, "TCP có cơ chế bắt tay 3 bước (3-way handshake) và đảm bảo gói tin đến đích theo thứ tự."],
    ["[Dễ] Dịch vụ thay phân giải tên miền thành địa chỉ IP được gọi là gì?", "A. DHCP", "B. DNS", "C. ARP", "D. NAT", 1, "DNS (Domain Name System) hoạt động chủ yếu trên port 53 UDP/TCP."],
    ["[Dễ] Cổng mặc định của giao thức HTTPS là bao nhiêu?", "A. 80", "B. 443", "C. 8080", "D. 21", 1, "HTTP dùng port 80, trong khi HTTPS (có mã hóa TLS/SSL) dùng mặc định là 443."],
    ["[Dễ] Tường lửa (Firewall) truyền thống (Stateful Firewall) thường lọc lưu lượng dựa trên yếu tố nào?", "A. Tên người dùng", "B. Nội dung của email", "C. IP nguồn, IP đích, Port và Giao thức", "D. Mã định danh phần cứng (MAC)", 2, "Các Rule của Firewall thường là dạng (Src_IP, Dst_IP, Protocol, Dst_Port, Allow/Deny)."],
    ["[TB] ARP Spoofing (Poisoning) – Giả mạo ARP thường được dùng để thực hiện cuộc tấn công nào trong mạng LAN?", "A. DDoS", "B. Man-in-the-Middle (MITM) – Xem trộm gói tin", "C. Password Brute-force", "D. SQL Injection", 1, "Attacker gửi bản tin ARP giả mạo để trình bày MAC của mình là Gateway, thu hút toàn bộ lưu lượng mạng nội bộ chạy qua máy Attacker."],
    ["[TB] IPSec hoạt động ở tầng nào của OSI và thường được ứng dụng để cấu hình cái gì?", "A. Tầng 7, dùng cho Web", "B. Tầng Tầng 3 (Network Layer) để cung cấp xác thực và mã hóa dữ liệu, thường dùng làm Site-to-Site VPN", "C. Tầng 4, cho mã độc", "D. Tầng 2, ảo hóa Switch", 1, "IPSec VPN rất phổ biến ở môi trường doanh nghiệp kết nối giữa các trụ sở thay vì truyền plaintext qua Internet."],
    ["[TB] Trong mã hóa, thuật toán RSA và thuật toán AES khác nhau ở điểm nào?", "A. RSA nhanh hơn AES", "B. AES là mã hóa bất đối xứng (dùng Public/Private key), RSA là mã hóa đối xứng", "C. AES dùng một khóa bí mật chung cho mã hóa/giải mã (Đối xứng), RSA dùng cặp khóa Công khai/Bí mật (Bất đối xứng)", "D. RSA dùng băm dữ liệu", 2, "Do tốc độ nhanh, thông thường RSA được dùng để trao đổi an toàn cái 'Khóa AES', sau đó luồng dữ liệu chính mã hóa bằng AES."],
    ["[TB] Thuật toán hàm băm (Hash) như SHA-256 có đặc điểm nổi bật nào?", "A. Nhỏ hơn MD5", "B. Dễ dàng giải mã ngược lại bản gốc", "C. Tính một chiều (One-way) và tạo ra một chuỗi độ dài cố định, tính chất chống va chạm (Collision resistance)", "D. Tạo ra chuỗi ngẫu nhiên mỗi lần chạy", 2, "Hash dùng để kiểm tra tính toàn vẹn (Integrity) của tập tin hoặc lưu mật khẩu."],
    ["[TB] IDS (Intrusion Detection System) khác IPS (Intrusion Prevention System) ở phản ứng đối phó với cảnh báo thế nào?", "A. IDS xóa mã độc, IPS báo cáo", "B. IDS là chỉ phát hiện và cảnh báo (Passive), IPS có khả năng tự chặn luồng độc hại bằng cách Tự động ngắt kết nối/Drop gói tin (Active)", "C. IPS nhanh hơn", "D. Không có khác biệt", 1, "IDS thường được SPAN/Mirror cổng switch lại để bắt gói tin mà không ảnh hưởng tới đường truyền."],
    ["[TB] Giao thức SMB (Server Message Block) của Microsoft rất quan trọng, nếu để mở qua Internet có thể bị các cuộc tấn công nổi tiếng nào đã từng tàn phá thế giới?", "A. Heartbleed", "B. WannaCry (Lỗ hổng EternalBlue - MS17-010)", "C. Log4Shell", "D. Shellshock", 1, "Lỗ hổng MS17-010 lợi dụng lỗi parse block của SMBv1 để RCE từ xa và phát tán Ransomware toàn cầu."],
    ["[Khó] Trong quá trình bắt tay TLS (TLS Handshake), thỏa thuận nào là cốt lõi để tạo ra đường hầm mã hóa bảo mật cuối cùng?", "A. Client kiểm tra thời tiết", "B. Tráo đổi mật khẩu Admin của Server", "C. Chọn Cipher Suite (bộ mã hóa hỗ trợ), kiểm tra Chứng chỉ số (Certificate), và sử dụng cơ chế trao đổi khóa phi đối xứng (vd: Diffie-Hellman) để lấy ra Session Key Master (Khóa đối xứng)", "D. Cả hai bên nhập mã CAPTCHA", 2, "Sau Handshake, TLS/SSL dùng khóa phiên đối xứng (Symmetric Session Key) bảo vệ dữ liệu trên quá trình trao đổi cho nhẹ."],
    ["[Khó] PKI (Public Key Infrastructure) là hạ tầng quản lý cái gì?", "A. Hệ thống tường lửa", "B. Hạ tầng khóa công khai, chịu trách nhiệm cho vòng đời (Tạo lập, Thu hồi, Quản lý) của các Chứng chỉ số X.509 dựa trên bên thứ ba được tin tưởng (Certificate Authority - CA)", "C. Thiết bị định tuyến", "D. Lưu trữ log hệ thống", 1, "Trình duyệt của bạn có sẵn Root Certificates của các tổ chức gốc như DigiCert (CA) để PKI tự động xác minh tính hợp lệ của server truy cập HTTPS."],
    ["[Khó] Kỹ thuật BGP Hijacking diễn ra như thế nào trên bình diện Internet diện rộng?", "A. Hack DNS server", "B. Lấy cắp mật khẩu router nhà nạn nhân", "C. Một AS (Autonomous System) công bố thông báo định tuyến giả (hoặc tối ưu hơn thực tế) về một dải IP Prefix, khiến cho các routers trên thế giới bị lừa và chuyển hướng lưu lượng truy cập quan trọng qua mạng của kẻ tấn công", "D. Dùng botnet tạo tải", 2, "BGP vốn tin cậy ngầm định các thông số được láng giềng advertise, nên rất dễ bị 'nhận vơ' nhà mạng, điều hướng lưu lượng Youtube/Facebook."],
    ["[Khó] Hoạt động của Perfect Forward Secrecy (PFS) có ý nghĩa chống lại cuộc tấn công nào mạnh nhất?", "A. Man-In-The-Middle thời điểm hiện tại", "B. DDoS", "C. Nếu Private Key tĩnh của máy chủ bị lộ TRONG TƯƠNG LAI, hacker vẫn KHÔNG THỂ giải mã được các luồng dữ liệu đã lưu hành (bị bắt gói tin) do các Session Key là tạm thời và không phụ thuộc vô Private key chính", "D. Phishing", 2, "ECDHE (Elliptic Curve Diffie-Hellman Ephemeral) là cơ chế PFS phổ biến trên Transport Layer Security (TLS 1.2+)."],
    ["[Khó] Một hệ thống Firewall thế hệ mới (NGFW) được tích hợp nhiều tính năng sâu, tính năng Deep Packet Inspection (DPI) làm gì?", "A. Chặn IP đen", "B. Định tuyến thông minh", "C. Thu thập và kiểm tra phần nội dung (Payload) lên tới tầng 7 của gói tin (Ví dụ: xem HTTP đang tải SQL Injection hay không) thay vì chỉ đọc Header", "D. Xem MAC address", 2, "NGFW (Palo Alto, Fortinet) có khả năng Application Awareness và IPS/AV signature based ngay trên box."]
];
