const autoToolQsRaw = [
    ["[Dễ] Ngôn ngữ kịch bản (Scripting Language) nào được sử dụng rộng rãi và phổ biến nhất, trở thành 'Ngôn ngữ mẹ đẻ' của Cybersecurity nhờ hệ sinh thái đồ sộ?", "A. C++", "B. Java", "C. Perl", "D. Python", 3, "Python có độ linh hoạt (Request, Scapy, BeautifulSoup, Pwntools, Impacket) tạo hiệu suất cao nhất để viết script Hacking / Automation."],
    ["[Dễ] Thư viện Python nổi tiếng nhất chuyên dùng để xử lý và phân tích/gửi nhận bắt gói tin mạng ở mức siêu thấp?", "A. Pandas", "B. Scikit-learn", "C. Scapy", "D. Matplotlib", 2, "Với Python Scapy bạn có thể can thiệp cả Header của Tầng lớp 2 (MAC) và Layer 3/4 để tạo giả mọi loại gói tin mạng tùy biến."],
    ["[Dễ] Khi cần trích xuất (Parsing) tự động hoặc gom dữ liệu có cấu trúc từ Logs, định dạng JSON hay được dùng vì sao?", "A. Nó đẹp hơn", "B. Chạy cực nhanh", "C. Là định dạng mô tả theo cặp Key-Value có cấu trúc rõ ràng, dễ đọc cho cả người và máy", "D. Chỉ cho hệ thống Apple", 2, "JSON thay thế XML nhờ tính gọn gàng."],
    ["[Dễ] Bash Script hay Bash Shell thường chạy natively (tự nhiên) trên hệ điều hành nào?", "A. Windows", "B. Tizen", "C. Linux / GNU Unix-like", "D. Android", 2, "DevSecOps hay System Admin Linux bắt buộc sành sõi Bash Scripting để gọi lệnh nội mạng OS siêu nhanh."],
    ["[TB] AI (LLM / Machine Learning) ứng dụng trong bảo mật tốt nhất ở khâu nào tại thời điểm hiện tại?", "A. Tự thay thế hoàn toàn CISO", "B. Chặn virus 100% không sai", "C. Phân tích ngữ cảnh logs lớn với công nghệ hỗ trợ truy vấn tự nhiên, tóm tắt sự cố mã độc, phát hiện bất thường hành vi mớ (Anomaly Detection)", "D. Cắm cáp mạng tự động", 2, "Cybersecurity Analytics có rất nhiều Alerts giả, AI giúp giảm tải việc phân loại false positive và gom cụm."],
    ["[TB] 'Regex' (Regular Expression - Biểu thức chính quy) làm nhiệm vụ gì trong lập trình Sec?", "A. Nén tập tin", "B. Một chuỗi các ký tự định nghĩa mẫu (pattern) đặc thù để CẮT, TRÍCH XUẤT, TÌM KIẾM chuỗi văn bản cực mạnh, (ví dụ: tìm IP, Mã thẻ tín dụng, Hash format trong đống log chục GB)", "C. Tạo file", "D. Kiểm tra mạng", 1, "Pattern matching của Regex không thể thiếu khi config rules SIEM/WAF hoặc log parsing."],
    ["[TB] 'Fuzzing' (Fuzz test) là kỹ thuật viết tool tự động làm gì để tìm lỗi (Bug/Zero-day)?", "A. Đẩy ngẫu nhiên hoặc có sửa lại hàng triệu dữ liệu (Mutated Data) đầu vào bất hợp lệ hoặc dị dạng vào một chương trình phần mềm với mục đích đợi chương trình đó sụp đổ (Crash) để nắm bắt Stack trace lỗi", "B. Quét danh bạ", "C. Hack mật khẩu Wifi tự động", "D. Tính điểm hệ thống", 0, "AFL (American Fuzzy Lop) là fuzzer đình đám đã tìm ra hàng nghìn vulnerabilities của các dự án nguồn mở C/C++."],
    ["[Khó] Trong Automation Pentest CI/CD (DevSecOps), công cụ DAST (Dynamic Application Security Testing) ví dụ OWASP ZAP cấu hình trên Pipeline kiểm tra phần mềm tại giai đoạn nào?", "A. Đọc file Source Code", "B. Giai đoạn Application đã được Build thành công và ĐANG CHẠY (Runtime/Deployment stage) để quét giao diện/Hành vi API thực tế phản hồi ra", "C. Vẽ bản đồ kết nối hạ tầng vật lý Docker", "D. Test Unit nội bộ", 1, "DAST là Black-box testing (Kiểm thử hộp đen) tự động tìm XSS/SQLi thay vì đọc code (SAST)."],
    ["[Khó] Bạn viết một Python Tool dùng module Selenium (WebDriver) chuyên phục vụ hành động gì hữu ích nhất cho Red Team?", "A. Gửi gói TCP siêu nhanh", "B. Viết mã tự động giả lập và gõ bàn phím từ một Trình duyệt y hệt người thật (Chrome, Fox), xử lý mượt JavaScript Rendering để Crawl Data hoặc Bypass CAPTCHA đơn giản (Web Scraping / Login Bruteforce GUI)", "C. Đọc file Hex", "D. Quản trị máy in mạng", 1, "Selenium / Puppeteer / Playwright xử lý Web Automation mạnh nhất hiện nay."]
];
