const socBlueQsRaw = [
    ["[Dễ] SoC (Security Operations Center) có nhiệm vụ trọng tâm gì hàng ngày?", "A. Dịch ngược mã độc", "B. Lập trình thêm ứng dụng phòng ban", "C. Giám sát an ninh mạng (Monitoring), phát hiện, phân tích và phản ứng lại các sự cố mạng/mã độc của tổ chức (Triage & Incident Response)", "D. Cấp phát laptop cho nhân sự", 2, "Tổ chức SOC hoạt động 24/7 để giám sát, giống như trung tâm camera an ninh."],
    ["[Dễ] Khái niệm SIEM (Ví dụ: Splunk, QRadar, IBM) là viết tắt của?", "A. System Incident Evaluation Method", "B. Security Intelligent Events Modeler", "C. Security Information and Event Management (Quản lý Thông tin và Sự kiện An ninh)", "D. Standard Integration Environment", 2, "SIEM gom (Aggregate) hàng triệu dòng log từ firewall, switch, windows... phân tích theo luật tương quan (Correlation Rules) để chỉ ra các cảnh báo (Offenses/Alerts)."],
    ["[Dễ] Trong mô hình IR của NIST (NIST SP 800-61), bước Preparation (Chuẩn bị) bao gồm các công việc gì?", "A. Cô lập server báo lỗi", "B. Phục hồi dữ liệu từ bản sao lưu", "C. Xây dựng chính sách, quy trình, tài liệu, công cụ và đào tạo nhân sự phòng SOC/CERT sẵn sàng cho trường hợp xảy ra sự cố", "D. Truy bắt hacker", 2, "Không chuẩn bị tốt sẽ vô cùng luống cuống khi sự cố thật xảy ra/bị Ransomware."],
    ["[Dễ] Nếu bạn phân tích một file .exe nghi ngờ và thấy nó cố kết nối tới một miền xyz123.com, domain này được gọi là gì trong Threat Intel?", "A. Nơi lưu trữ đám mây", "B. C&C (Command and Control) Server của kẻ tấn công", "C. DNS Server dự phòng", "D. Gateway gốc", 1, "Mã độc liên lạc 'về nhà' để nhận lệnh (như tải thêm payload hoặc nhận khóa mã hóa)."],
    ["[Dễ] Tác dụng chính yếu nhất khi đưa một địa chỉ IP C&C vào danh sách đen (Blacklist) Firewall tổ chức là?", "A. Gọi điện cho nhà cái", "B. Tăng tốc mạng", "C. Ngăn các máy trạm nhiễm mã độc trong mạng LAN gọi ra ngoài chờ lệnh, cắt đứt sự điều khiển của hacker", "D. Hacker bị bắt", 2, "Containment (Ngăn chặn) là mục tiêu sống còn đầu tiên của Analyst."],
    ["[TB] MITRE ATT&CK Framework chia luồng tấn công thành các TTPs. Trong đó TTPs là viết tắt của?", "A. Trust, Time, Procedure", "B. Tactics, Techniques, and Procedures (Chiến thuật, Kỹ thuật và Quy trình)", "C. Tactics, Technology, Protocols", "D. Tools, Triage, Penetration", 1, "TTP mô tả hành vi của Kẻ Tấn Công thay vì chỉ dựa và Hash hay IP. Báo cáo APT lúc nào cũng mapping TTP."],
    ["[TB] Lateral Movement (Di chuyển ngang) trong chuỗi quy trình của Cyber Kill Chain có nghĩa là:", "A. Copy file từ ổ C sang ổ D", "B. Hacker thay đổi IP liên tục", "C. Hacker xâm nhập một máy A thành công, rồi dùng máy đó làm bàn đạp tấn công các máy tính khác B,C bên trong mạng LAN nội bộ ngang hàng", "D. Mã hóa theo chiều ngang màn hình", 2, "Giúp Hacker tìm tới máy chủ cao cấp hơn hoặc Domain Controller."],
    ["[TB] Giải pháp SOAR (Security Orchestration, Automation, and Response) hỗ trợ Analyst điều gì vượt trội hơn SIEM đơn thuần?", "A. Quét virus nhanh hơn", "B. Không những phân tích, SOAR sử dụng các kịch bản chạy tự động (Playbooks) để kích hoạt API chặn IP trên Firewall, xóa tài khoản tự động mà không cần can thiệp thủ công từ đầu đến cuối", "C. Đổi pass hệ thống", "D. Tạo backup tự động", 1, "SOAR giải quyết bài toán mỏi gối phồng tay vì Fatigue (Mệt mỏi) của Analyst do Alerts SIEM quá nhiều."],
    ["[TB] Khi bạn là Analyst thấy có một lượng lớn 'Login Failed' event code liên tục với một UserName từ nhiều nguồn IP lạ, bạn kết luận:", "A. Do lỗi bàn phím", "B. Người dùng quên mật khẩu", "C. Tấn công Password Brute-force/Credential Stuffing hay Password Spraying", "D. Tấn công SQLi", 2, "Gây lock account AD hoặc dò trúng mật khẩu yếu cùa người dùng hệ thống."],
    ["[TB] Một IOC (Indicator of Compromise) điển hình dựa trên Network thường được SOC/BlueTeam truy dấu qua yếu tố nào?", "A. Đơn xin nghỉ phép", "B. Hash của file chứa payload", "C. Các giá trị như IP độc hại, Tên miền DGA, chuỗi User-Agent dị biệt được lưu trong gói tin Proxy Logs / DNS Logs", "D. Phím F5", 2, "Hash là của File/Host-based. Network dựa vào traffic flows."],
    ["[Khó] Trong quá trình Thăm dò bộ nhớ trực tiếp trên Windows (Memory Forensics) để phân tích tiến trình, nếu một đoạn thực thi có quyền PAGE_EXECUTE_READWRITE vô danh (không trỏ tới tệp đĩa nào), nó cảnh báo về nguy cơ gì?", "A. Ổ cứng hỏng sektor", "B. Chương trình chạy do quản trị tự kích hoạt", "C. Tấn công Fileless Malware, dùng kỹ thuật Process Injection (chèn shellcode thẳng vào bộ nhớ), hay Reflective DLL loading", "D. Game sử dụng card rời", 2, "Mã độc hiện đại né tránh AV/Disk bằng cách chạy thẳng trên vùng nhớ RWX, để trốn."],
    ["[Khó] Kỹ thuật 'Living off the Land' (LotL) mà các bản tin Threat Intel hay đề cập nhằm mô tả hiện tượng nào?", "A. Tấn công đánh bom", "B. Thay vì tải tools của mình xuống, hacker sử dụng các công cụ/Tiện ích có sẵn mặc định trên Hệ điều hành đích (vd: PowerShell, WMI, Certutil, MSHTA) để thực hiện các hành vi độc hại", "C. Chôn thiết bị hacking", "D. Dùng IP Việt Nam", 1, "Rất khó cho SOC phát hiện vì các tiến trình PowerShell.exe chạy là chuyện hợp pháp của Windows, phải soi kĩ Arguments của command-line."],
    ["[Khó] Kỹ thuật phân tích Logs hệ thống quy mô lớn (Log Hunting) thường yêu cầu các Analyst phải hiểu về Windows Event Tracing (ETW) vì ?", "A. Nhẹ tài nguyên", "B. Có thể lấy mật khẩu", "C. ETW giúp ghi lại các sự kiện ở mức độ Kernel (hành vi chi tiết như Network Connections, File IO, Process Create) với tốc độ cao, được EDR sử dụng sâu mà hacker khó có thể tắt hay che giấu hơn các Event Log chuẩn", "D. Giao thức UDP", 2, "Kiểm chứng Process/Thread activity cực kì hiệu quả."]
];
