const grcQsRaw = [
    ["[Dễ] Mô hình cốt lõi nhất của An toàn thông tin (CIA Triad) bao gồm 3 yếu tố nào?", "A. Cyber, Intelligence, Agency", "B. Confidentiality (Bảo mật), Integrity (Toàn vẹn), Availability (Sẵn sàng)", "C. Control, Incident, Asset", "D. Core IT Architecture", 1, "Mọi nỗ lực bảo mật chung quy đều để bảo vệ 3 tính chất sống còn này của Dữ liệu."],
    ["[Dễ] ISO 27001 là tiêu chuẩn quốc tế nổi bật quy định về hệ thống nào?", "A. Quản lý chất lượng sản phẩm", "B. Quản lý rủi ro cháy nổ", "C. Hệ thống Quản lý An toàn Thông tin (ISMS)", "D. Phát triển web an toàn", 2, "ISO/IEC 27001 là chứng chỉ mà hầu hết danh nghiệp uy tín đều phấn đấu đạt được để chứng minh tính chuyên nghiệp bảo mật."],
    ["[Dễ] Mục tiêu chính của Tính Toàn vẹn (Integrity) trong CIA là gì?", "A. Giữ bí mật dữ liệu không cho ai xem", "B. Đảm bảo dữ liệu không bị sửa đổi trái phép một cách cố ý hoặc vô tình (Vd: số dư tài khoản ngân hàng)", "C. Làm hệ thống chạy nhanh hơn 24/7", "D. Cấp quyền truy cập hệ thống", 1, "Băm (Hash) và Chữ ký số (Digital Signature) là công cụ toán học bảo vệ Integrity."],
    ["[Dễ] Theo công thức đánh giá rủi ro cơ bản, Rủi ro (Risk) được lượng hóa bằng tích số của 2 nhân tố chính nào?", "A. Tài sản và Hệ điều hành", "B. Lỗ hổng (Vulnerability) và Sự cố (Incident)", "C. Khả năng xảy ra (Likelihood / Probability) X Mức độ tác động/Thiệt hại (Impact / Consequence)", "D. Tấn công (Attack) và Phản ứng (Response)", 2, "Ma trận Rủi ro (Risk Matrix) thường xếp hạng màu Đỏ (Cao) khi cả khả năng xảy ra và hậu quả đều Lớn."],
    ["[Dễ] Nếu bạn làm mất một chiếc USB chứa danh sách 1 triệu khách hàng chưa mã hóa, yếu tố nào của CIA bị vi phạm trực tiếp nhất?", "A. Sẵn sàng", "B. Toàn vẹn", "C. Bảo mật (Confidentiality)", "D. Không bị vi phạm gì", 2, "Dữ liệu bị lộ cho bên thứ ba không có thẩm quyền là định nghĩa của Information Disclosure / Breach."],
    ["[TB] PDPA (Nghị định 13/2023/NĐ-CP tại Việt Nam) tập trung chủ yếu vào quy định bảo vệ đối tượng nào?", "A. Máy chủ nhà nước", "B. Giao dịch tiền mã hóa", "C. Dữ liệu cá nhân (Personal Data) và quyền riêng tư của công dân", "D. An ninh mạng doanh nghiệp", 2, "NĐ 13 quy định cách tổ chức thu thập, lưu trữ, và bảo vệ Dữ liệu cá nhân hợp pháp."],
    ["[TB] Quyền 'Privacy' (Quyền riêng tư) khác 'Security' (Bảo mật) ở điểm nào?", "A. Privacy dùng mật khẩu yếu hơn", "B. Security là việc khóa cửa, còn Privacy là quyền bạn quyết định ai được xem bên trong và sử dụng thông tin đó thế nào", "C. Không khác biệt", "D. Privacy đắt tiền hơn", 1, "Security là giải pháp kỹ thuật/Quy trình. Privacy là vấn đề pháp lý, thỏa thuận về sự đồng thuận (Consent)."],
    ["[TB] Chuẩn bảo mật PCI-DSS (Payment Card Industry Data Security Standard) có tính chất bắt buộc đối với tổ chức nào?", "A. Bệnh viện", "B. Công ty phát triển Game", "C. Các ngân hàng, tổ chức/doanh nghiệp có lưu trữ, xử lý, truyền tải dữ liệu thẻ thanh toán (Credit/Debit Card)", "D. Trường học", 2, "Hội đồng thẻ quốc tế (Visa, MasterCard...) cấm ngặt các điểm bán hàng lưu số CVV và plain-text của dải băng từ."],
    ["[TB] Trong quản lý rủi ro (Risk Management), phương thức 'Chấp nhận rủi ro' (Risk Acceptance) thường được chọn trong hoàn cảnh nào?", "A. Không bao giờ", "B. Nếu chi phí để khắc phục (Mitigation Cost) lớn hơn hẳn giá trị tổn thất nếu rủi ro xảy ra, Lãnh đạo sẽ ký giấy chấp nhận bù đắp thiệt hại", "C. Bị phạt từ chính quyền", "D. Rủi ro quá lớn gây phá sản", 1, "Việc khắc phục phải hợp lý về mặt tài chính (Cost-Benefit Analysis)."],
    ["[TB] SOC Type 2 (System and Organization Controls 2) Audit kiểm tra điều gì của một Vendor (nhà cung cấp Cloud/SaaS)?", "A. Doanh thu của Vendor", "B. Khả năng phòng ngự vật lý của trụ sở chính", "C. Tính hiệu quả (Effectiveness) của các biện pháp bảo mật (Security, Availability, Processing Integrity, Confidentiality, Privacy) của tổ chức đó trong một THỜI GIAN DÀI (ví dụ: 6-12 tháng)", "D. Hệ điều hành nội bộ", 2, "SOC2 báo cáo cho các khách hàng (B2B) thấy rằng bạn giữ vững cam kết Security của mình trong thực tế chứ không phải hứa suông."],
    ["[Khó] Trong thiết kế Chính sách truy cập (Access Policy), 'Separation of Duties' (Phân tách Trách nhiệm) giúp chống lại rủi ro trọng yếu nào?", "A. Làm tốn thời gian", "B. Mâu thuẫn logic lập trình", "C. Gian lận nội bộ (Internal Fraud) do không có cá nhân nào được phép kiểm soát toàn bộ chu trình hoàn chỉnh của một quy trình nhạy cảm (A-Z)", "D. DDoS", 2, "Ví dụ kinh điển là Kế toán soạn phiếu chi không được phép tự duyệt chi, phải là Kế toán trưởng duyệt."],
    ["[Khó] RTO (Recovery Time Objective) và RPO (Recovery Point Objective) trong Business Continuity Plan (BCP) lần lượt định nghĩa các tham số gì?", "A. Ngân sách và Số người tham gia", "B. Khoảng thời gian downtime hệ thống TỐI ĐA cho phép (RTO) VÀ Khoảng thời gian dữ liệu MẤT MÁT TỐI ĐA chấp nhận được do backup (RPO)", "C. Thuê ngoài (RTO) và Phát triển In-house (RPO)", "D. Số giờ fix bug (RTO) và Số phút server khởi động lại (RPO)", 1, "RPO càng nhỏ (tiến về 0 giây) thì giải pháp sao lưu Mirror/Real-time chi phí càng tốn kém định mức Enterprise."]
];
