const cloudSecQsRaw = [
    ["[Dễ] Hệ thống Docker cô lập các ứng dụng bằng công nghệ của Linux Kernel tên là gì?", "A. Sandbox App", "B. Hypervisor ESXi", "C. Namespaces (phân biệt tài nguyên) và Cgroups (giới hạn tài nguyên)", "D. Mật khẩu Root", 2, "Namespace tách biệt PIDs, Mạng, Mount. Cgroups phân bổ tỷ lệ CPU/RAM."],
    ["[Dễ] Thành phần nào đóng vai trò như 'Nhà kho' lưu trữ và quản lý các Docker Image chứa mã nguồn/dịch vụ của tổ chức?", "A. Docker Compose", "B. Docker Swarm", "C. Container Registry (ví dụ Docker Hub, AWS ECR, Harbor)", "D. Docker File", 2, "Bảo mật Registry (Scan lỗ hổng images trước khi kéo) là cực chuẩn DevSecOps."],
    ["[Dễ] Nếu bạn để tệp Dockerfile chứa lệnh `ENV DATABASE_PASSWORD=secret123`, nguy cơ bảo mật lớn nhất là gì?", "A. File to hơn", "B. Bí mật (Secrets) bị lộ cứng trong Image, bất kỳ ai có hoặc Inspect lớp Image đều đọc trộm được", "C. Bị báo lỗi biên dịch", "D. Database crash", 1, "Hardcoded secrets trong Dockerfile/Code là sai lầm bảo mật kinh điển ở Cloud/DevOps."],
    ["[Dễ] Nền tảng nào được sử dụng phổ biến nhất để Điều phối và Quản lý cụm Container trong quy mô khổng lồ của các hãng Cloud?", "A. Terraform", "B. Kubernetes (K8s)", "C. Jenkins", "D. Ansible", 1, "Hệ sinh thái kiến trúc microservices hiện đại dùng trái tim là Kubernetes."],
    ["[Dễ] Trong Cloud Security (AWS/Azure), ai là người chịu rách nhiệm về an ninh hệ điều hành trong mô hình máy chủ ảo IaaS (Infrastructure as a Service)?", "A. Khách hàng (Bạn)", "B. Nhà cung cấp Cloud", "C. Chính phủ", "D. Không ai", 0, "Theo mô hình chia sẻ trách nhiệm (Shared Responsibility Model), Cloud bảo vệ phần cứng vật lý nền tảng. Khách hàng lo Hệ Điều Hành (Patching, Firewall, Data)."],
    ["[TB] Mục đích của một 'Security Group' trên AWS (hoặc NSG trên Azure/VNPT Cloud) tương tự với khái niệm nào trong DataCenter truyền thống?", "A. UPS", "B. Server Proxy", "C. Stateful Firewall áp dụng tại card giao tiếp mạng ảo (vNIC) bảo vệ truy cập (Allow In/Out Ports)", "D. Switch L2", 2, "SG chặn từ xa traffic độc hại trước cả khi chạm vào OS ảo của bạn."],
    ["[TB] Lỗ hổng SSFR (Server-Side Request Forgery) trên nền tảng AWS nguy hiểm đột biến hơn ở môi trường vật lý vì kẻ tấn công thường nhắm vào địa chỉ IP đặc thù nào?", "A. 1.1.1.1", "B. 8.8.8.8", "C. Địa chỉ Metadata Services (IMDS): 169.254.169.254", "D. 192.168.1.1", 2, "Gọi 169.254.169.254/latest/meta-data/iam/security-credentials/ sẽ trả về IAM Role Temporary Keys Token có thể dùng để điều khiển toàn bộ tài khoản AWS của nạn nhân."],
    ["[TB] Khái niệm 'Least-Privileged IAM Role' trong Cloud quy định gì cho ứng dụng backend (EC2)?", "A. Không cấp quyền bảo mật gì cả", "B. Cấp AdministratorAccess", "C. Chỉ cung cấp Role có đúng policy Read vào S3 Bucket nếu nó chỉ dùng để đọc ảnh thư viện, không có quyền xóa bucket hay chạm vào RDS/Database", "D. Để Role công khai Public", 2, "Bị chiếm Instance => Kẻ thù lấy vai trò (Role) đó. Rủi ro phụ thuộc vào policy của chính Role."],
    ["[TB] Phương thức an toàn nhất nào để Pod ứng dụng (App Container) truyền tải và quản trị Token API/DB Password ở Kubernetes?", "A. Viết thẳng vào source code", "B. Lưu ở configmap plaintext", "C. Các tính năng như Kubernetes Secrets, hoặc External Vault Manager (HashiCorp Vault) được mount mã hóa/inject lúc Pod chạy để tránh rò rỉ", "D. Gửi qua Slack", 2, "Quản trị định danh và Bí mật (Secret Management) là thiết yếu khi quy mô k8s phình to."],
    ["[Khó] Trong môi trường K8s, Kỹ thuật khai thác 'Kubernetes Pod Escape' (Thoát kén) thường thành công lớn nhất nếu quản trị viên vô tình vi phạm thiết lập nào cho Deploy?", "A. Để Resource Limits lớn", "B. Không cấu hình Ingress", "C. Triển khai Container với thông số 'privileged: true' (Quyền hạn đầy đủ của host node) hoặc mount Host /var/run/docker.sock vào Pod vào Pod", "D. Config HPA sai (Auto-scale)", 2, "Privileged pod có tất cả Linux Capabilities tương tự root node thật sự => Cgoup mount cgroup exploit thẳng cẳng host."],
    ["[Khó] Serverless Computing (ví dụ AWS Lambda, Google Cloud Function) trong Cloud Security có điểm khác biệt cốt lõi nào so với IaaS khi kiểm thử bảo mật lỗ hổng mã nguồn (Web/App)?", "A. Không cần bảo vệ dữ liệu", "B. Không thể dùng WAF bảo vệ", "C. Attacker có được RCE cũng rất khó giữ kết nối vì ứng dụng là máy ảo ngắn hạn (Ephemeral), tự hủy sau mili-giây/giây xử lý, không có Persistent Layer cho Shell", "D. Máy ảo Serverless không xử lý API", 2, "Để khai thác serverless, hacker không tập trung tạo Reverse shell lâu dài mà lấy cặp Key IAM sinh ra tại thời gian thực."],
    ["[Khó] RBAC (Role-Based Access Control) của Kubernetes. Cặp đối tượng/Action (Quyền) nào sau đây bị cảnh báo đỏ (Red flag) nếu một ServiceAccount được cấp, dẫn đến chi phối mức cao nhất?", "A. get pods", "B. 'create' vào 'pods/exec'", "C. list services", "D. watch configmaps", 1, "Exec vào pod tương đương việc leo vào terminal bash của Container, có thể chứa mật khẩu root hoặc network bridge nhạy cảm nội bộ K8s."]
];
